name: Build Release
on: [push, workflow_dispatch]

jobs:

  build:
    permissions: write-all
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Visual Studio
        run: "C:"

      - run: |
          & dir "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/"

      - name: Setup Visual Studio Build Environment
        run: |
          "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvarsall.bat" amd64 && nmake
        shell: cmd
